### ISSUE TITLE
Cache file is converted to .htm

### ISSUE THREAD

**Issue by AbramF** [GustavBrock/VBA.PictureUrl#2]
Hi,

When I try to use this function for my images, my URLs ends with a .jpg. The cache file is however saved as .htm-files. The MS Access-file cannot display that file type. I have looked at the URLDownloadToCacheFile documentation, but I cannot find a way to avoid convertion of the file at download. Even in your example code, your picture is changed from .jpg to .png (but that is still ok for the image control in Access).

Is there a way to force URLDownloadToCacheFile to keep original file format? In that case, it should be included in your function to improve performance.

My pictures that I have is stored in a Sharepoint Document Library, which I have full access rights for. Could this be a part of the issue?

**Comment by GustavBrock** [comment]
If you - on-line (in the browser) - right-click a picture in Sharepoint and select "copy link", it will copy a link to the page holding the picture, not to the picture file itself, and this is a htm link, thus the download file will be a link having the htm extension.

There is no way _URLDownloadToCacheFile_ can convert a file; it does a plain download, that's all - which also is why it is so fast.
