### ISSUE TITLE
Getting Weather Info

### ISSUE THREAD

**Issue by jsnstwrd** [GustavBrock/VBA.PictureUrl#3]
Thanks for pointing me to this "Issues" link.  I will send you as much information as possible to help figure out how to import weather data on 64bit MS Access 2016.   1st:  Is this normal for code to be red?

![image](https://user-images.githubusercontent.com/105895129/169427207-797a5918-4895-4cea-9e70-63523767dfb7.png)

**Comment by jsnstwrd** [comment]
This is from your code:       FileName = "C:\Test\WeatherData.csv"
There is no "Test" folder created when I click your button.  This is what I get when I search C: for "WeatherData" and double click one of those "WeatherData" links:

![image](https://user-images.githubusercontent.com/105895129/169427948-3025a7ed-2b1e-4f85-be86-784b72652c02.png)



And this is what I get when I click "Yes":

![image](https://user-images.githubusercontent.com/105895129/169428009-ea487f56-2ce1-4e69-a306-c4c47ec91941.png)

**Comment by jsnstwrd** [comment]
Is it possible to skip the download to hard drive step and download data directly to the MS Access table?

**Comment by GustavBrock** [comment]
> Is this normal for code to be red?

Yes. That's the code for pre-VBA7 only (Access 2007 and earlier).

**Comment by GustavBrock** [comment]
> There is no "Test" folder created when I click your button. 

True. It will not create any folder. Either create your own C:\Test folder, or decide for an existing folder and then adjust the code accordingly.

**Comment by GustavBrock** [comment]
> Is it possible to skip the download to hard drive step and download data directly to the MS Access table?

No. The link is for a file generated by the weather site on request. But as small as it is, it will download and attach in a second.

**Comment by jsnstwrd** [comment]
Wow!  That’s what it was the whole time.  #1 It can’t be any One Drive folders (which you told me).  #2 You have to first create the folder.  I created the “Test” folder on C: and tried again….   It worked.  Thanks so much!!!

**Comment by GustavBrock** [comment]
Great! Have a nice weekend!
