### ISSUE TITLE
Doesn't Overwrite Existing Files

### ISSUE THREAD

**Issue by jsnstwrd** [GustavBrock/VBA.PictureUrl#4]
The code is working well.  However, once "WeatherData.csv" exists, it is not overwritten with the next button press.  Is there a modification that can be made to your code that performs the action of first checking if file exists, deleting it if it exists, then continue with the download?

**Comment by GustavBrock** [comment]
If the table is open in Access, it is locked and cannot be deleted, thus neither be overwritten.

If you close the table, the file will be overwritten.
However, the current code will, following successful download, create a _new_ link, "WeatherData1". 
To avoid that, extend Module1 to hold this code, that checks if the file already has been linked:

```
Option Compare Database
Option Explicit

Public Function LinkData()

    Dim Url         As String
    Dim FileName    As String
    Dim Success     As Long
    
    Url = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/garden%20city%2C%20tx?unitGroup=us&elements=datetime%2Ctempmax%2Cprecip%2Cpreciptype%2Cwindgust%2Cwindspeed&include=days&key=KVP7BF7EYTKGZK236GEFF4RGX&contentType=csv"
    FileName = "C:\Test\WeatherData.csv"
    
    Success = DownloadFile(Url, FileName)
    If Success = 0 Then
        If Not IsTable("WeatherData") Then
            DoCmd.TransferText acLinkDelim, , "WeatherData", FileName, True
        End If
    End If

End Function

Public Function IsTable(ByVal TableName As String) As Boolean

    Dim Table       As DAO.TableDef
    
    For Each Table In CurrentDb.TableDefs
        If Table.Name = TableName Then
            Exit For
        End If
    Next
    
    IsTable = CBool(Not Table Is Nothing)
    
End Function
```

**Comment by jsnstwrd** [comment]
Ok.  Thanks.  I understand that file won’t delete if it’s open.  However, the code only works if the file doesn’t already exist at C:/Test.  I don’t need anything to delete the linked file in Access.  I need to delete the local file at C:/Test if it exists.  The link would remain viable because file names are the same.

**Comment by jsnstwrd** [comment]
I misunderstood the code.  It performs as requested.  Thanks!

 

 

 

 

From: ***@***.*** ***@***.***> 
Sent: Saturday, May 21, 2022 10:46 AM
To: 'GustavBrock/VBA.PictureUrl' ***@***.***>; 'GustavBrock/VBA.PictureUrl' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [GustavBrock/VBA.PictureUrl] Doesn't Overwrite Existing Files (Issue #4)

 

Ok.  Thanks.  I understand that file won’t delete if it’s open.  However, the code only works if the file doesn’t already exist at C:/Test.  I don’t need anything to delete the linked file in Access.  I need to delete the local file at C:/Test if it exists.  The link would remain viable because file names are the same.

**Comment by GustavBrock** [comment]
Great! Thanks for the feedback.
